name: Deploy DevOps Project

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Mensaje CI/CD
      run: echo "Pipeline ejecutado correctamente"
